### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by gdk-gagan** [pyviz-demos/minimal-heroku-demo#1]
I am trying to deploy the given notebook on Heroku, and getting following errors - 

2019-10-10T18:56:34.175664+00:00 heroku[web.1]: Starting process with command `panel serve --address="0.0.0.0" --port=35641 iris_kmeans.ipynb --allow-websocket-origin=iris-kmeans.herokuapp.com`
2019-10-10T18:56:35+00:00 app[api]: Build succeeded
2019-10-10T18:56:39.084115+00:00 heroku[web.1]: Process exited with status 1
2019-10-10T18:56:39.16523+00:00 heroku[web.1]: State changed from starting to crashed
2019-10-10T18:56:38.858497+00:00 app[web.1]: **ERROR: The Bokeh notebook application handler requires Jupyter Notebook to be installed.**

Tried adding 'jupyter' to requirements.txt, and pushing to heroku master. It runs the app but just gives a blank page.

Appreciate any help!

**Comment by philippjfr** [comment]
Did you follow this part of the instructions?

> the websocket origin should match the name of the app on Heroku app-name.herokuapp.com which you will declare in the next step:

**Comment by skrishnakumar00** [comment]
Hi,
Got the same error that gdk-gagan got.  Followed the above instructions about "websocket origin...", still issue persisted.

I then moved my code to a .py file and executed. Am able to deploy, but the webpage does not show any output. When i try my code with .show(), it works perfectly (localhost page shows proper output).

So it seems that .servable() is giving some problem. Have used the exact procfile u have provided in this repo (after updating my app name).

Request ur inputs to resolve. Thanks!

**Comment by skrishnakumar00** [comment]
Hi,
Could solve the issue
1. In Requirements.txt, we need to include Jupyter
2. All other libraries we are using in our code, need to be mentioned in Requirements.txt. Including even regular packages like pandas, numpy etc.
3. I had missed couple of them, hence my app was not working

Thanks

**Comment by philippjfr** [comment]
Sorry for not getting to this sooner, and really appreciate you reporting back on this.

**Comment by skrishnakumar00** [comment]
No issues at all :-) Hope you are safe and in good health.

**Comment by aspitarl** [comment]
Just adding that to get this to work I also had to add 'jupyter' to requirements.txt, but that was it.

**Comment by philippjfr** [comment]
Thanks @aspitarl for reminding me about this. I think what's actually needed is `nbconvert` so I've added that. Please reopen if this is still an issue.
